# Generated by Django 3.2.6 on 2021-08-03 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryboy_catlog_bonous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delevered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.deliveryboy'),
        ),
    ]
