# Generated by Django 3.2.6 on 2021-08-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_order_delevered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='amounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonous', models.IntegerField(default=0)),
                ('penality', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryboy_catlog',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
